# Changes here will be overwritten by Copier
_commit: v1.4.6
_src_path: gh:lincc-frameworks/python-project-template
author_email: malanchev@cmu.edu
author_name: LINCC Frameworks
create_example_module: true
custom_install: true
include_benchmarks: true
include_docs: true
include_notebooks: true
mypy_type_checking: basic
package_name: pandas_ts
preferred_linter: black
project_license: MIT
project_name: pandas-ts
project_organization: lincc-frameworks
use_isort: true
