# This workflow runs pre-commit hooks on pull requests to enforce coding style.
# To ensure correct configuration, please refer to:
#   https://lincc-ppt.readthedocs.io/en/latest/practices/ci_precommit.html

name: Run pre-commit hooks

on:
  pull_request:

jobs:
  pre-commit-ci:
    runs-on: ubuntu-latest
    env: 
      SKIP: "check-lincc-frameworks-template-version,pytest-check,no-commit-to-branch,validate-pyproject,check-added-large-files,sphinx-build"
    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: 0 
    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        sudo apt-get update
        python -m pip install --upgrade pip
        pip install .[dev]
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - uses: pre-commit/action@main # Still using Node 16
      with:
        extra_args: --from-ref ${{ github.event.pull_request.base.sha }} --to-ref ${{ github.event.pull_request.head.sha }}
    - uses: pre-commit-ci/lite-action@main
      if: always()